# Welcome to Jekyll!
#

# Site settings
title: Space Apps Zaragoza
description: |
  3 y 4 de octubre
owner: Space Apps Zaragoza
first_published: 2020
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sazgz.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/spaceappszgz
  github: https://github.com/sazgz

# Build settings
markdown: kramdown
#sass:
#  style: compressed
